# Azure DevOps pipeline for Maven project

trigger:
- master

pool:
  name: Default
  demands:
    - agent.name -equals LAPTOP-23VP4VGF

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false

- task: PublishTestResults@2
  inputs: 
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'JUnit test results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'MyArtifact'
    publishLocation: 'Container'


